### ISSUE TITLE
Paused not working

### ISSUE THREAD

**Issue by lieven121** [smartenergycontrol-be/home-assistant-smappee-charging-profiles#1]
![image](https://github.com/user-attachments/assets/2ce7f7be-a291-4851-b4e7-67a1d0475ced)

I found a bug when setting mode to paused 

this is the card i use 

show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: smappee_charging_profiles.set_charging_mode
  data:
    serial: 'redacted'
    mode: PAUSED
  target: {}
name: Pause Charger
icon: fapro:pause
layout_options:
  grid_columns: 1
  grid_rows: 3

when i try it in developser tools i get an unkown error

it does work with Normal mode

Let me also thank you for setting this up

**Comment by scruysberghs** [comment]
hadn't tested PAUSED yet. Committed a small fix that should fix this... 
Have the UI set up like this now with a slider and and a mode selector
![image](https://github.com/user-attachments/assets/b9eb4e2b-0783-4f99-95d9-75d504e7af3e)

**Comment by lieven121** [comment]
Can confirm it works
