### ISSUE TITLE
Feature request: adding multiple devices, splitting up charge calls

### ISSUE THREAD

**Issue by lieven121** [smartenergycontrol-be/home-assistant-smappee-charging-profiles#2]
Would you consider adding serial number to the config

For managing multiple devices, you would then have to add multiple entries (and add a device to the entry)
![image](https://github.com/user-attachments/assets/958b8c82-1b08-4569-af1d-98fa16df7135)

This would allow you to provide services based on a 'device'
Then you could split up following calls
Set charger to Normal (allow a number input or an entity)

Set charger to Paused

Set charger to Smart

**Comment by scruysberghs** [comment]
It could be done automatically. I recently found the serial(s) in the "Get metering configuration" api https://smappee.atlassian.net/wiki/spaces/DEVAPI/pages/916422661/Get+metering+configuration
Would allow you to add al the charging stations and all connectors (some have 2). Can't test however as I only have one charging station with one connector in my "servicelocation"

**Comment by scruysberghs** [comment]
> Would you consider adding serial number to the config
> 
> For managing multiple devices, you would then have to add multiple entries (and add a device to the entry) ![image](https://private-user-images.githubusercontent.com/7773244/371888284-958b8c82-1b08-4569-af1d-98fa16df7135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTY0ODMsIm5iZiI6MTcyNzg5NjE4MywicGF0aCI6Ii83NzczMjQ0LzM3MTg4ODI4NC05NThiOGM4Mi0xYjA4LTQ1NjktYWYxZC05OGZhMTZkZjcxMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTkwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU1Y2I5ZmY0ODQzZjUxOTZmYTU3NDgyODllYzM4ZDBlYzc2YzYyYTAwNzkwN2UyMjQxZjQzMTMwZDAyNjYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rLzQ9XKV4VczjWJ3QWGTH64vQiI_zKip3iWiU1P41so)
> 
> This would allow you to provide services based on a 'device' Then you could split up following calls Set charger to Normal (allow a number input or an entity)
> 
> Set charger to Paused
> 
> Set charger to Smart

you can easily add multiple automations (one per serialnr) in home assistant for that with the integration as it is now. Would give you a drop down with mode selector and slider with power per charging station.
![image](https://github.com/user-attachments/assets/34cd50c0-b4dc-4ccc-84b4-842d94239e38)

**Comment by weha** [comment]
> you can easily add multiple automations (one per serialnr) in home assistant for that with the integration as it is now. Would give you a drop down with mode selector and slider with power per charging station. 

I have an EV ONE but PAUSED does nothing.
I also don't have PAUSED as a type in the app?
I see 3 types, Normal, Smart and Leftover
There is a separate boolean that enables or disables the EV ONE

**Comment by lieven121** [comment]
Paused is a state in normal

![Screenshot_20241010_135852_Smappee.jpg](https://github.com/user-attachments/assets/b85d04ff-241c-4df3-9d8a-55b1733bc231)

**Comment by weha** [comment]
> Paused is a state in normal
> 

well ok but it still does not do anything when you send it, it remains "available"
Neither does LEFTOVER or SURPLUS, FYI

**Comment by royalidea** [comment]
> > Would you consider adding serial number to the config
> > For managing multiple devices, you would then have to add multiple entries (and add a device to the entry) ![image](https://private-user-images.githubusercontent.com/7773244/371888284-958b8c82-1b08-4569-af1d-98fa16df7135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTY0ODMsIm5iZiI6MTcyNzg5NjE4MywicGF0aCI6Ii83NzczMjQ0LzM3MTg4ODI4NC05NThiOGM4Mi0xYjA4LTQ1NjktYWYxZC05OGZhMTZkZjcxMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTkwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU1Y2I5ZmY0ODQzZjUxOTZmYTU3NDgyODllYzM4ZDBlYzc2YzYyYTAwNzkwN2UyMjQxZjQzMTMwZDAyNjYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rLzQ9XKV4VczjWJ3QWGTH64vQiI_zKip3iWiU1P41so)
> > This would allow you to provide services based on a 'device' Then you could split up following calls Set charger to Normal (allow a number input or an entity)
> > Set charger to Paused
> > Set charger to Smart
> 
> you can easily add multiple automations (one per serialnr) in home assistant for that with the integration as it is now. Would give you a drop down with mode selector and slider with power per charging station. ![image](https://private-user-images.githubusercontent.com/58264733/373000911-34cd50c0-b4dc-4ccc-84b4-842d94239e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzUyNzUsIm5iZiI6MTczMTA3NDk3NSwicGF0aCI6Ii81ODI2NDczMy8zNzMwMDA5MTEtMzRjZDUwYzAtYjRkYy00Y2NjLTg0YjQtODQyZDk0MjM5ZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE0MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDkyOTQxYjM1ZDZlOTYyNjRhZTBlZTBjNWNhMWIzMDE5MTY2ZTUwNzUzMTNlMjIxMjc3N2ZhNWFhODQ3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eIz8kQW06Hvud-qp2l1PcsBLyWIwF3ELQvbTdJ-n1CA)

How do you create this UI element?

**Comment by scruysberghs** [comment]
> 
> How do you create this UI element?

Pasted a basic howto in the wiki https://github.com/smartenergycontrol-be/home-assistant-smappee-charging-profiles/wiki

You can easily change the automations to do solar surpluss charging or set it to auto charging only when priced drop below a certain pricepoint if you have a dynamic energy contract...
