### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by driesvandamme** [smartenergycontrol-be/home-assistant-smappee-charging-profiles#4]
I'm trying to execute the service through the helper in HomeAssistant

However, I get an error.. Not sure if I'm doing something wrong?

--> Actie smappee_charging_profiles.set_charging_mode kon niet worden uitgevoerd. Unknown error

**Comment by scruysberghs** [comment]
are you sure you used the correct serial number in the action call? Should be a 10 digit number that starts with a 6. You can find it in the smappee app or trough the "Get metering configuration" api call https://smappee.atlassian.net/wiki/spaces/DEVAPI/pages/916422661/Get+metering+configuration

**Comment by lieven121** [comment]
I get an error too but seems (for me) to be related to the refresh token, as when i setup the integration it works for a while but then stops working

**Comment by driesvandamme** [comment]
My bad! Was using wrong serial number :)

Could you update the docs to see which modes are available?

**Comment by lieven121** [comment]
![image](https://github.com/user-attachments/assets/e2952fa3-28a3-4d22-a601-3da10359a327)
here util docs have it :)

**Comment by driesvandamme** [comment]
In the app there is also the option to switch to "Injection-based charging" (if you have solar panels)
Is there an option to switch back to that?

I'd like to make Smappee charge automatically when there is enough solar energy predicted (before Home battery is full)
- Since smappee's "injection mode" only starts after the Home Battery is full, it starts charging quite late..

Would be ideal if I could make it switch between NORMAL/INJECTION based charging like this :-)

**Comment by scruysberghs** [comment]
> I get an error too but seems (for me) to be related to the refresh token, as when i setup the integration it works for a while but then stops working

a fix for that was comiitted a couple af days ago but haven't had the chance to test myself. Update/redownload the integration trough hacs and let me know i

**Comment by lieven121** [comment]
> In the app there is also the option to switch to "Injection-based charging" (if you have solar panels) Is there an option to switch back to that?
> 
> I'd like to make Smappee charge automatically when there is enough solar energy predicted (before Home battery is full)
> 
> * Since smappee's "injection mode" only starts after the Home Battery is full, it starts charging quite late..
> 
> Would be ideal if I could make it switch between NORMAL/INJECTION based charging like this :-)

This mode is called SOLAR but isnt officialy supported, since mine isn't working right now maybe you can try and set SOLAR as mode and see if it works

**Comment by lieven121** [comment]
> > I get an error too but seems (for me) to be related to the refresh token, as when i setup the integration it works for a while but then stops working
> 
> a fix for that was committed a couple af days ago but haven't had the chance to test myself. Update/redownload the integration trough hacs and let me know i

i tried this,
this is the 'version' i use 
![image](https://github.com/user-attachments/assets/32fcf7e8-8ec9-4dfe-bb28-18302dd7763c)
![image](https://github.com/user-attachments/assets/12b1c9bd-fb87-4763-bd50-98dee26a5770)

**Comment by lieven121** [comment]
> > In the app there is also the option to switch to "Injection-based charging" (if you have solar panels) Is there an option to switch back to that?
> > I'd like to make Smappee charge automatically when there is enough solar energy predicted (before Home battery is full)
> > 
> > * Since smappee's "injection mode" only starts after the Home Battery is full, it starts charging quite late..
> > 
> > Would be ideal if I could make it switch between NORMAL/INJECTION based charging like this :-)
> 
> This mode is called SOLAR but isnt officialy supported, since mine isn't working right now maybe you can try and set SOLAR as mode and see if it works

@driesvandamme  Sadly it doesnt work 
![image](https://github.com/user-attachments/assets/4e99d8a3-d68a-4d5a-b1a5-10799eaa0bf3)

**Comment by driesvandamme** [comment]
Indeed / Had the same result when I tested.
- I sent an email to smappee support earlier today asking if they could add it / if they have a reason not expose that functionality over their API. (I don't think it should take them very long to implement it) + It works in the app, so I don't see why they wouldn't allow it ..

Not sure how responsive they are, but seems they are missing quite some functionality compared to other brands :-(

You never know...

**Comment by scruysberghs** [comment]
> Indeed / Had the same result when I tested.
> 
>     * I sent an email to smappee support earlier today asking if they could add it / if they have a reason not to expose that functionality over their API. (I don't think it should take them very long to implement it) + It works in the app, so I don't see why they wouldn't allow it ..
> 
> 
> Not sure how responsive they are, but seems they are missing quite some functionality compared to other brands :-(
> 
> You never know...

are you sure this isn't what "SMART" charging is supposed to do? (don't know as there is no solar where I am testing the Smappee charging)

**Comment by scruysberghs** [comment]
but using the action call in this integration you can make your own logic trough home assistant automations. No need for the Smappee charging station to be SMART at all. Just let Home Asssitant be the master. I use EMHASS to do day ahead planning/optimizations looking at solar forecast and dynamic pricing. It makes a day ahead schedule for deferable loads (water heating, heat pump, swimming pool etc), car charging and house battery charging and discharging.

**Comment by lieven121** [comment]
Ooh i use epex spot + solar forecast + a sonnen home battery but for now its a very manual process for me which i hope to automate

What does the evcc.io addon do and how does it communicate with smappee?

**Comment by scruysberghs** [comment]
evcc.io addon gives you a nice ui/ux the set the charging modes, planning charging sessions etc (for example I need to drive 300 kilometers tomorrow). It can't talk to Smappee directly at the moment (it could trough ocpp but then you need to get your service whitelisted trough Smapee support) but it can talk to anything in Home Assistant. 
It has support to read SoC from many car brands and chargers (more than Home Assistant has)

**Comment by driesvandamme** [comment]
@scruysberghs - Could be interesting to be able to set the "Capaciteitstarief" / Maximum Peak Wattage using the API as well.
Don't know if you found anything to do that yet by any chance?

**Comment by scruysberghs** [comment]
> @scruysberghs - Could be interesting to be able to set the "Capaciteitstarief" / Maximum Peak Wattage using the API as well. Don't know if you found anything to do that yet by any chance?

Sure.
You can do that by dividing your desired or current capaciteitstarief by 240V is you have a 1f charger and by 3x240V if you have 3f charging. 

If you want to keep below 3000W for example set the charger amperage to 3000/240=12,5A so 12 in this case as the Smappee api only accepts integers (1f charging)

If you have 3f charging you can't set it below 4320W=3*6A*240V
You can make a template sensor to calculate max charging current using a input number or the value from your p1 meter to set the max capaciteitstarief and use that number to call the Smappee service in an automation.

something like {{ states('sensor.maximum_month_demand')  | float(0) - states('sensor.current_import_from_grid')  | float(0) / 240 }} to use this months peak read from your p1 meter or {{ states('input_number.max_capaciteitstarief') - states('sensor.current_import_from_grid')  | float(0) / 240 }} 

Replace the sensor names to match how you measure power from grid in your system.

(next time make a new topic for questions unrelated to the topic please, I'll close this "issue")
